package com.jml.reconciliation.model.enums;

public enum EventType {
    RECONCILIATION_STARTED,
    DATA_SOURCE_UNAVAILABLE,
    DATA_SOURCE_STALE,
    ISSUE_DETECTED,
    REMEDIATION_CREATED,
    REVIEW_REQUESTED,
    APPROVAL_GRANTED,
    APPROVAL_REJECTED,
    ACCESS_REMOVED,
    ACCESS_REDUCED,
    ROLLBACK_EXECUTED,
    DATA_SOURCE_HEALTH_CHANGED
}
